In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("customers.csv")
accounts = pd.read_csv("accounts.csv")
transactions = pd.read_csv("transactions.csv")
cards = pd.read_csv("cards.csv")
loans = pd.read_csv("loans.csv")
merchants = pd.read_csv("merchants.csv")
branches = pd.read_csv("branches.csv")

In [3]:
customers.head()

,customer_id,first_name,last_name,email,city,credit_score,created_at
0,CUSXAJI0Y6DPBHS,Kevin,Young,brauncameron@example.net,North Williamville,327,4/17/2025
1,CUSHXTHV3A3ZMF8,Jason,Clements,toddwilliam@example.net,Martinezside,644,2/23/2020
2,CUSDD4V30T9NT3W,Randy,Thompson,trevoranderson@example.org,Gallowayfurt,670,6/22/2025
3,CUSGCX1945NQ4FM,Laura,Phillips,valdezgeorge@example.com,Morrisview,573,10/20/2019
4,CUSVG0FN9XUY41I,Savannah,Swanson,smithluis@example.com,Lake Anna,332,7/16/2022

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   50000 non-null  object
 1   first_name    50000 non-null  object
 2   last_name     50000 non-null  object
 3   email         50000 non-null  object
 4   city          50000 non-null  object
 5   credit_score  50000 non-null  int64
 6   created_at    50000 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.7+ MB

In [5]:
customers.describe()

       credit_score
count  50000.000000
mean     574.490520
std      158.692145
min      300.000000
25%      437.000000
50%      575.000000
75%      712.000000
max      850.000000

In [6]:
customers.describe(include='object')

,customer_id,first_name,last_name,email,city,created_at
count,50000,50000,50000,50000,50000,50000
unique,50000,690,1000,45773,25169,2557
top,CUSXAJI0Y6DPBHS,Michael,Smith,yjohnson@example.com,South Michael,1/30/2020
freq,1,1161,1094,9,51,35

In [7]:
customers.shape()

TypeError: 'tuple' object is not callable

In [8]:
customers.shape

(50000, 7)

In [9]:
customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'city',
       'credit_score', 'created_at'],
      dtype='object')

In [10]:
customers.dtypes

customer_id     object
first_name      object
last_name       object
email           object
city            object
credit_score     int64
created_at      object
dtype: object

In [11]:
customers.isnull().sum()

customer_id     0
first_name      0
last_name       0
email           0
city            0
credit_score    0
created_at      0
dtype: int64

In [12]:
customers.duplicated().sum()

np.int64(0)

In [13]:
import numpy as np